name: Zip Repo and Generate Checksum

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive repository
      run: |
        zip -r ARDAudiothek.zip . -x "*.github/*"
        
    - name: Generate checksum
      run: |
        sed -i "/checksum/{s/checksum/$(sha1sum ARDAudiothek.zip | awk '{print $1}')/}" repo.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ARDAudiothek
        path: ARDAudiothek.zip
